services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    container_name: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-scripts/dump5.sql:/docker-entrypoint-initdb.d/dump5.sql # this is the path to the sql file
    ports:
      - '5432:5432'
    networks:
      - app-network
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 5s
      timeout: 5s
      retries: 5

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    container_name: nest-pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=pgadmin4
    ports:
      - '5050:80'
    depends_on:
      db:
        condition: service_healthy
    networks:
      - app-network

  # redis:
  #   image: redis
  #   container_name: redis
  #   ports:
  #     - '6379:6379'
  #   networks:
  #     - app-network
  #   restart: always

volumes:
  postgres_data:
    name: postgres_data

networks:
  app-network:
    driver: bridge
